USE bd_carro;

-- > SELECIONA TODOS OS REGISTROS
SELECT * FROM tb_proprietario;
SELECT * FROM tb_carro;

-- > SELECIONA APENAS COLUNAS ESPECIFICADAS
SELECT marca, modelo FROM tb_carro;

-- > SELECIONA O MAIOR 'VALOR' DE UMA COLUNA ESPECIFICADA DO DATABASE
SELECT MAX(valor) FROM tb_carro;

-- > SELECIONA O MENOR 'VALOR' DE UMA COLUNA ESPECIFICADA DO DATABASE
SELECT MIN(numero_vendas) FROM tb_carro;

-- > SELECIONA ELEMENTO ESPECIFICO DO DATABASE
SELECT * FROM tb_carro WHERE id = 2;
SELECT * FROM tb_proprietario WHERE nome = 'Rafael';
SELECT * FROM tb_carro WHERE cor = 'Preto';


-- > SELECIONA O MAIOR E MENOR 'VALOR' REGISTRADO + AS COLUNAS ESPECIFICADAS DO DATABASE
SELECT marca, modelo, ano FROM tb_carro WHERE valor = (SELECT MIN(valor) FROM tb_carro);

